run:
  timeout: 5m

linters:
  enable:
    - govet
    - revive
    - ineffassign
    - staticcheck
    - misspell
    - gosimple
    - typecheck
    - errcheck
    - gofmt
    - unparam
    - goconst
    - gosec

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        arguments:
          - "disableStutteringCheck"
      - name: var-naming
      - name: indent-error-flow
      - name: error-return
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0